language: node_js
node_js:
  - "10"
cache:
  directories:
    - code/node_modules
before_script:
  - cd code && npm install
script:
  - cd code && npm run build
notifications:
  email: false
branches:
  only:
      - master
deploy:
  provider: pages
  local-dir: code/dist
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  fqdn: proto.school
  on:
    branch: master
