name: Daily Build (events and Mailchimp subscription updates)
on:
  schedule:
    - cron: '0 9 * * *' # everyday at 9am
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Trigger build
      run: curl -H "Authorization:${{ secrets.FLEEK_API_KEY }}" -H "Content-Type:application/json" -d '{"query":"mutation { triggerDeploy(siteId:\"${{ secrets.FLEEK_SITE_ID }}\") { status } }"}' https://api.fleek.co/graphql
